### ISSUE TITLE
Add command to mark merge request as ready or in progress

### ISSUE THREAD

**Issue by profclems** [profclems/glab#17]
**Is your feature request related to a problem? Please describe.**
Merge requests with status WIP or Draft cannot be merged as they are considered not ready.
There should be a command to mark merge requests as ready so they can be merged.

**Describe the solution you'd like**
Add a command:
```bash
# Mark as ready
glab mr status ready

# Mark as work in progress
glab mr status wip
```

**Describe alternatives you've considered**
```bash
# Mark as ready
glab mr status remove wip

# Mark as work in progress
glab mr status add wip

```

**Comment by pgollangi** [comment]
From the gitlab [documentation](https://docs.gitlab.com/ee/user/project/merge_requests/work_in_progress_merge_requests.html#removing-the-draft-flag-from-a-merge-request), adding a note to merge request will toggle `wip` or `draft`. But it will just be toggle, but not add or remove. I think this should be fine if we can add a column to `mr list` results to inform user about MR wip status (`WorkInProgress:true`) since ideally user would lists the MRs first and then updates it with one of resulted MR `ID`

If this is acceptable, a new command can be introduced for [quick actions](https://docs.gitlab.com/ee/user/project/quick_actions.html#quick-actions-for-issues-merge-requests-and-epics). `wip` would be part of it.

**Comment by pgollangi** [comment]
I'm not sure of `go-gitlab` support of it yet. I'll check and update. Action command would gentrify all actions on MR. It would be something like `glab mr action wip`. 

Actually it will become an alternative way for all current actions implemented. For example to reopen `glab mr action reopen`  and  `glab mr reopen` are same.

**Comment by pgollangi** [comment]
I think no special support from `go-gitlab` required since this should be done via notes API.

**Comment by profclems** [comment]
I think I should have closed this issue since we added additional flags (`wip` and `drafit`) to `mr create` in [09ba137](https://github.com/profclems/glab/commit/acf2e6e7f7419312a62f51c3bf24cc9fc0d95c33)

**Comment by pgollangi** [comment]
Okay. Do you think marking MR `wip` after creating it is not a priority for now?

**Comment by profclems** [comment]
I think that can be done with `glab mr update` where you can change the title and add `WIP` or `Draft` to the title.
I will add `wip` and `draft` flag to `mr update` to simplify that
