### ISSUE TITLE
Implement glab repo fork command 

### ISSUE THREAD

**Issue by solidnerd** [profclems/glab#347]
**Is your feature request related to a problem? Please describe.**
As a Go Developer or working with OSS projects a lot. I mostly fork the repository and do the changes and contribute it back. I want to have an easy way of creating a fork and clone it locally

**Describe the solution you'd like**
An implementation of `glab repo fork`

What it does: 

1. Create a fork for the requested repo via GitLab API
2. Do a `git clone` of the forked repository
3. Add a `git remote add upstream` automatically to the forked repo from the upstream repository.

**Describe alternatives you've considered**
/
**Additional context**
Here is an example with `gh repo fork`

```sh
$ gh repo fork profclems/glab
- Forking profclems/glab...
✓ Created fork solidnerd/glab
? Would you like to clone the fork? Yes
Cloning into 'glab'...
remote: Enumerating objects: 465, done.
remote: Counting objects: 100% (465/465), done.
remote: Compressing objects: 100% (271/271), done.
remote: Total 6905 (delta 206), reused 366 (delta 167), pack-reused 6440
Receiving objects: 100% (6905/6905), 20.63 MiB | 11.56 MiB/s, done.
Resolving deltas: 100% (4706/4706), done.
Updating upstream
From https://github.com/profclems/glab
 * [new branch]      dependabot/go_modules/github.com/xanzy/go-gitlab-0.40.1 -> upstream/dependabot/go_modules/github.com/xanzy/go-gitlab-0.40.1
 * [new branch]      profclems-patch-1                                       -> upstream/profclems-patch-1
 * [new branch]      trunk                                                   -> upstream/trunk
✓ Cloned fork
```

**Comment by zemzale** [comment]
Thanks for the suggestion.
This seems like a nice feature.

The forking can be done using [projects api](https://docs.gitlab.com/ee/api/projects.html#fork-project). Then it's just matter of waiting for fork to be completed since it's a background job and cloning it if user wants to do that. 

The only thing I think we should consider is how we determine which of the authenticated hosts to use

In my head I have two solutions 
- Just ask the user which host to use
- Check each of the authenticated hosts, if the project exists there, and then fork it. In this way it would be more seamless and we wouldn't have to ask for user input. If there are multiple places where project exist(which is probably not the case most of the time, but could be a thing), then we just ask the user which instance to use.
