### ISSUE TITLE
Implement clone of repositories from a GitLab Group

### ISSUE THREAD

**Issue by solidnerd** [profclems/glab#348]
**Is your feature request related to a problem? Please describe.**

It's quite hard to clone a whole group at once for this you typically bash scripts for python scripts for doing this job. But I would like to have it integrated.

**Describe the solution you'd like**

`glab repo clone -g everyonecancontribute`

1. clone the group of `everyonecancontribute` with all Projects and Sub Groups with  

**Describe alternatives you've considered**
/

**Additional context**
/

**Comment by zemzale** [comment]
I agree that this would be a nice thing to have. I have wrote scripts in the past to do this myself, a simple command from `glab` would be great timesaver.

We can use the [groups api](https://docs.gitlab.com/ee/api/groups.html#list-a-groups-projects) for this. 
Implementation would be just calling this API and cloning the repos.

The one thing I have a question about is should we clone archived projects by default too? Since they are readonly I would imagine that they don't have real value for most of the use cases anyways, so we could just omit them. If user really wants to clone archived projects that could be done using a flag.

**Comment by profclems** [comment]
This is really a standout feature for `glab` if implemented. I will start putting together solutions right away

> The one thing I have a question about is should we clone archived projects by default too? Since they are readonly I would imagine that they don't have real value for most of the use cases anyways, so we could just omit them. If user really wants to clone archived projects that could be done using a flag.

I think by default `glab` should clone all the group projects including the archived ones but there should be flags to limit the types of projects to clone

**Comment by zemzale** [comment]
> I think by default glab should clone all the group projects including the archived ones but there should be flags to limit the types of projects to clone

This probably is better way clone everything and explicitly filter things if you wish, instead of silently filtering stuff.
