### ISSUE TITLE
Pipeline views: Display failed pipelines that allow failure diferently 

### ISSUE THREAD

**Issue by zemzale** [profclems/glab#373]
In commands like `pipeline status` and `pipeline view` there is no indications  that pipeline is allowed to fail e.g.
![image](https://user-images.githubusercontent.com/14844365/102188283-c59bdf80-3ebd-11eb-92b9-5810afc216a6.png)
while in Web UI it shows up like 
![image](https://user-images.githubusercontent.com/14844365/102188411-ecf2ac80-3ebd-11eb-8608-150a7186f1c0.png)

**Propose a Solution**
Display pipelines that are allowed to fail differently, indicating that, it's okay to merge with that job failing.
For `pipeline ci view` I would propose just changing the color of said job.
In `pipeline status` it would probably be differen't text in differen't color too I supposes. Something like `passed with warnings`

**Additional context**
This would be only changes to the output of the commands, since the attribute `allow_failure` is already in the API we are using https://docs.gitlab.com/ce/api/jobs.html#list-pipeline-jobs

**Comment by profclems** [comment]
I have also noticed another issue with the `pipeline status`. Instead of showing the duration like `0m 55s`, it is formatted using the [PrettyTimeAgo](https://github.com/profclems/glab/blob/f77f183455f49e292757305b225ec49534decb14/internal/utils/utils.go#L54) func  so it displays `less than a minute ago` 

https://github.com/profclems/glab/blob/f77f183455f49e292757305b225ec49534decb14/commands/pipeline/status/pipeline_status.go#L81
