### ISSUE TITLE
Allow CI pipelines to be displayed with the flow from left to right, rather than right to left

### ISSUE THREAD

**Issue by unikitty37** [profclems/glab#432]
**Describe the feature or problem you'd like to solve**
When viewing a pipeline in GitLab's web interface, the first stage is displayed on the left, and the pipeline flows from left to right. In `glab pipeline ci view`, this is reversed.

I find this confusing to navigate, as:

* it differs from what GitLab presents;
* my language (English) runs from left-to-right, so this is the order I'm used to seeing things progress in.

I don't know Go well enough to trace through the code particularly well, but it looks like right-to-left is hardcoded, rather than there being a way to reverse it that I simply haven't found.

**Propose a Solution**
It would be easiest if GLab checked the locale and rendered pipelines left-to-right in locales that use left-to-right languages, and right-to-left in locales that use right-to-left languages; this should automatically do the right thing in most cases.

It might be necessary to override this in some cases (such as where a locale is handled incorrectly) — a `--reverse` flag to `glab pipeline ci view` might be the best option here, although ideally it would be settable through `glab config` so it can be overridden per-repo, per-host, or globally, without the need to add a flag each time.

**Additional context**
My current locale-related environment, which should give left-to-right:

```
LANG=en_GB.UTF-8
LC_ALL=en_GB.UTF-8
LC_CTYPE=en_GB.UTF-8
```

**Comment by profclems** [comment]
I suspect that the change comes from the GitLab Jobs API, probably newer versions of GitLab, which now returns the jobs based on their ID in descending order.

Thanks for reporting.

It should be fixed by #442.

Not related but you should note that for newer versions of `glab` ([v.1.13.0+](https://github.com/profclems/glab/releases)), you should use `glab ci view` instead of `glab pipeline ci view`. See #372
