### ISSUE TITLE
Move hosting to GitLab

### ISSUE THREAD

**Issue by ShakataGaNai** [profclems/glab#67]
Call it a "Feature request", but it seems kinda wrong to be hosting GitLab tools on GitHub. So I'd suggest moving this repository over to GitLab. Perhaps it could be left as a read-only mirror on GitHub.

**Comment by profclems** [comment]
Thank you @ShakataGaNai 
I hosted it here on GitHub for OSS visibility; a lot of people find it convenient to contribute to FOSS on GitHub. 
However, it is hosted on Gitlab as well as a mirror from this GitHub repo.
https://gitlab.com/profclems/glab

**Comment by profclems** [comment]
@zemzale what do you think about this issue? 
I recently had the chance to talk with GitLab's Open Source Program Manager and she suggested we move the hosting to GitLab. 
Personally, I'm okay with it here because we are already using [GitLab CI](https://github.com/profclems/glab/blob/trunk/.gitlab-ci.yml) to run the tests and we have a mirror on [GitLab](https://gitlab.com/profclems/glab).
I still hold on to this [comment](https://github.com/profclems/glab/issues/67#issuecomment-670254381):

> I hosted it here on GitHub for OSS visibility; a lot of people find it convenient to contribute to FOSS on GitHub.

Personally, I use GitLab heavily at work and GitHub for personal projects

**Comment by zemzale** [comment]
I think for the moment the OSS visibility is really the main reason why we should stay on GitHub. 
I love using GitLab and I use it way more for personal and work related things, but I strongly believe that the visibility is not there for OSS projects.
