### ISSUE TITLE
scriptability: avoiding ellipsize (...) of columns/lines

### ISSUE THREAD

**Issue by quite** [profclems/glab#706]
Great improvements on this in https://github.com/profclems/glab/issues/258 -- but glab still abbeviates long lines/columns with ellipsis (...) if they don't fit in the terminal. This is always done, even if PAGER is not used. But in particular, piping to `grep` or otherwise redirect the output for a non-human reader, really becomes useless when things are shortened, ellipsized.

I'm not sure if the best way would be to have a flag that tells glab to not do this. I'm more used to programs that does not do these kind of things at all by default, but maybe I/they are old-fashioned? :)

By the way, the unicode `…` should probably be used instead of `...` when this is actually done (as unicode is already used elsewhere in glab).

**Comment by zemzale** [comment]
Thanks for the brought-up issue @quite. 

There are actually a few commands(`mr view` and `issue view`) that check if they are printing to tty before printing the output, and if they are not they just print out everything without any styling or cutting text.

To improve upon this we just need to figure out which commands actually make sense to be printed to non-tty (example: `ci view` doesn't make sense since it's an interactive command, but maybe there is a case for a non-interactive output too)

From the top of my head prime candidates for commands that need a raw output would be 
- `mr list`
- `issue list`
- `ci list`

This could be pretty simple to implement so if anyone wants to work on this this is open for PRs.
