### ISSUE TITLE
Add commit bodies on MRs with multiple commits

### ISSUE THREAD

**Issue by guyfedwards** [profclems/glab#795]
**Describe the feature or problem you'd like to solve**

Creating an MR with multiple commits, I would like to have the commit bodies added to the MR description as well as the titles

**Propose a Solution**

Up to you whether this should be the default (same as single commit MRs) or behind an additional flag such as `--fill-body` or something. 
This can be added [here](https://github.com/profclems/glab/blob/0fb95eab621e8ea12d1a870889c6f29a72caa9aa/commands/mr/create/mr_create.go#L504) where the commit titles are currently being added.

**Additional context**

I can work on this, just wanted to get thoughts on the flag.

**Comment by zemzale** [comment]
I agree that this would be a pretty nice addition, but I think this probably should be under a flag. In scenarios where commit messages are very huge, or someone really doesn't care about them it would just be annoying to them.

I think you can easily work on that. I am just more interested of @profclems thoughts on the flag name.

**Comment by profclems** [comment]
Not quite sure what the flag name should be. It's difficult choosing a flag name that matches its purpose.

To highlight on the behaviour of the `--fill` flag, it fills both the title and body of the MR with the commit title and body respectively (but for single commit). When there are multiple commits available, it will use the commit titles as the MR body (if no description is provided with `--description`) and the branch name as MR title (if no title is provided with `--title`).

Since `--fill-body` literally means that it fills only the body of the MR, we can use that for now (unless someone has a better name?? @zemzale). Any changes that come up will be suggested in the PR review.


We also need to decide on how display commit bodies and titles in the MR body. Should it be:

```
- commit one
body of commit one.
Lorem ipsum dolor sit amet, consectetur adipiscing elit, 
sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. 

- commit two
body of commit 
Lorem ipsum dolor sit amet, consectetur adipiscing elit, 
sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. 
```

or 

```
commit one - body of commit one. 
Lorem ipsum dolor sit amet, consectetur adipiscing elit, 
sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. 

commit two - body of commit two. 
Lorem ipsum dolor sit amet, consectetur adipiscing elit, 
sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. 
```

@guyfedwards in your use case, how would you want it?

**Comment by guyfedwards** [comment]
Another option for the flag could be `--fill-commit-body` if that is more explicit. In terms of the formatting I was thinking like your first example. 

```
- commit one
body of commit one.
Lorem ipsum dolor sit amet, consectetur adipiscing elit, 
sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. 

- commit two
body of commit 
Lorem ipsum dolor sit amet, consectetur adipiscing elit, 
sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. 
```

**Comment by zemzale** [comment]
I actually prefer the more explicit `--fill-commit-body` flag. And the way how the body is filled looks good too.
